services:
  discordBot:
    build:
      context: .
      dockerfile: Telegram.DiscordBot/Dockerfile
    image: bot/discordbot:latest
  telegramBot:
    build:
      context: .
      dockerfile: Telegram.TelegramBot/Dockerfile
    image: bot/telegrambot:latest