services:
  discordBot:
    build:
      context: .
      dockerfile: Telegram.DiscordBot/Dockerfile
    image: bot/discordbot:latest
  telegramBot:
    build:
      context: .
      dockerfile: Telegram.TelegramBot/Dockerfile
    ports:
      - 8080:8080
    image: bot/telegrambot:latest