name: CI/CD with Docker Compose

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull repo
        uses: actions/checkout@v3

      - name: Stop and remove current containers
        run: |
          docker-compose down || true

      - name: Build and start containers
        run: |
          echo "${{ secrets.APPSETTINGS_TELEGRAM }}" > src/Telegram.TelegramBot/appsettings.json
          echo "${{ secrets.APPSETTINGS_DISCORD }}" > src/Telegram.DiscordBot/appsettings.json
